### ISSUE TITLE
Lightsaber crashes on JVM 17+

### ISSUE THREAD

**Issue by BraisGabin** [SchwarzIT/dagger-lightsaber#102]
When we run Lightsaber on a JVM 17+ the compilation crashes with this message:

```
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

And it seems that the root case is this part of this stacktrace:

```
Caused by: java.lang.IllegalAccessError: class schwarz.it.lightsaber.FindingKt (in unnamed module @0x70a32d3b) cannot access class com.sun.tools.javac.model.JavacElements (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.model to unnamed module @0x70a32d3b
	at schwarz.it.lightsaber.FindingKt.getCodePosition(Finding.kt:37)
	at schwarz.it.lightsaber.FindingKt.getCodePosition$default(Finding.kt:32)
	at schwarz.it.lightsaber.domain.ModuleJavac$Binding.getCodePosition-impl(Module.kt:98)
	at schwarz.it.lightsaber.domain.ModuleJavac$Binding.getCodePosition(Module.kt:97)
	at schwarz.it.lightsaber.checkers.UnusedBindsAndProvidesKt.checkUnusedBindsAndProvides(UnusedBindsAndProvides.kt:27)
	at schwarz.it.lightsaber.LightsaberBindingGraphPlugin$visitGraph$issues$5.invoke(LightsaberBindingGraphPlugin.kt:42)
	at schwarz.it.lightsaber.LightsaberBindingGraphPlugin$visitGraph$issues$5.invoke(LightsaberBindingGraphPlugin.kt:41)
	at schwarz.it.lightsaber.LightsaberBindingGraphPluginKt.runRule(LightsaberBindingGraphPlugin.kt:85)
	at schwarz.it.lightsaber.LightsaberBindingGraphPluginKt.access$runRule(LightsaberBindingGraphPlugin.kt:1)
	at schwarz.it.lightsaber.LightsaberBindingGraphPlugin.visitGraph(LightsaberBindingGraphPlugin.kt:41)
	at dagger.internal.codegen.validation.ExternalBindingGraphPlugins.visitPlugins(ExternalBindingGraphPlugins.java:127)
	at dagger.internal.codegen.validation.ExternalBindingGraphPlugins.visit(ExternalBindingGraphPlugins.java:99)
	at dagger.internal.codegen.validation.BindingGraphValidator.visitExternalPlugins(BindingGraphValidator.java:86)
	at dagger.internal.codegen.validation.BindingGraphValidator.isValid(BindingGraphValidator.java:63)
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:117)
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.process(ComponentProcessingStep.java:87)
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.process(ComponentProcessingStep.java:49)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:82)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:68)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:70)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.spi.shaded.androidx.room.compiler.processing.XProcessingStep.process(XProcessingStep.kt:59)
	at dagger.spi.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:130)
	at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.process(JavacBasicAnnotationProcessor.kt:73)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:209)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
	... 39 more
```

**Comment by BraisGabin** [comment]
The issue is related with the java modules and Lightsaber using internal apis. Right now we don't have other option than using those APIs to get our error messages but we will keep researching to avoid this issue.

Meanwhile to workaround the issue you can compile with this argument: `--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED`.

If you use gradle you should add it to the `gradle.properties` file:

```properties
org.gradle.jvmargs=--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
```
