### ISSUE TITLE
Add support for project isolation

### ISSUE THREAD

**Issue by NikolayMetchev** [SchwarzIT/dagger-lightsaber#277]
It would be good to get a head start on adding support for project isolation to this plugin.
Project isolation is documented here:
https://docs.gradle.org/current/userguide/isolated_projects.html

On my project I get the following problems currently:
```
- [error] Project `:services:auth:db:dao` cannot access `Project.group` functionality on another project `:utils:mapstruct:spi`
    - plugin 'io.github.schwarzit.lightsaber'
        - Exception at `schwarz.it.lightsaber.gradle.processors.ProcessorKt.isDaggerCompiler(Processor.kt:30)`
org.gradle.api.InvalidUserCodeException: Project ':services:auth:db:dao' cannot access 'Project.group' functionality on another project ':utils:mapstruct:spi'
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getGroup(Unknown Source)
	at schwarz.it.lightsaber.gradle.processors.ProcessorKt.isDaggerCompiler(Processor.kt:30)
	at schwarz.it.lightsaber.gradle.processors.ProcessorKt.access$isDaggerCompiler(Processor.kt:1)
	at schwarz.it.lightsaber.gradle.processors.ProcessorKt$withDaggerCompiler$4.invoke(Processor.kt:17)
	at schwarz.it.lightsaber.gradle.processors.ProcessorKt$withDaggerCompiler$4.invoke(Processor.kt:15)
	at schwarz.it.lightsaber.gradle.processors.ProcessorKt.withDaggerCompiler$lambda$0(Processor.kt:15)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by BraisGabin** [comment]
I can't reproduce that error. Could you provide a sample project?

**Comment by BraisGabin** [comment]
I can reproduce it on my project now. Now I need to find a way to reproduce it on tests.
